# Generated by Django 4.2.3 on 2023-07-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeCategoria", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeProduto", models.CharField(max_length=50)),
                ("descricaoProduto", models.CharField(max_length=200)),
                ("precoProduto", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
