# Generated by Django 4.2.3 on 2023-07-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeProduto", models.CharField(max_length=50)),
                (
                    "descricaoProduto",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("precoProduto", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "categoriaProduto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configa.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.DeleteModel(
            name="Produtos",
        ),
    ]
